name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for better Git info
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install sphinx sphinx-rtd-theme myst-parser sphinx-autodoc-typehints
        # Install package dependencies
        if [ -f pyproject.toml ]; then
            pip install -e .
        elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
        fi
    
    - name: Build documentation
      run: |
        cd docs
        # Copy .nojekyll to build directory
        cp .nojekyll _build/.nojekyll 2>/dev/null || touch _build/.nojekyll
        sphinx-build -b html . _build -W --keep-going
    
    - name: Upload documentation artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs/_build
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
        publish_branch: gh-pages
        force_orphan: true
